services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apit-api
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - sqlite_data:/data
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: sqlite
      DB_DATABASE: /data/database.sqlite

volumes:
  sqlite_data:
